#Codigos de tabla en MySQL

CREATE TABLE ROLES (
    IdRol BIGINT AUTO_INCREMENT PRIMARY KEY,
    Descripcion VARCHAR(250)
);

CREATE TABLE TIPODOCUMENTO (
    IdTipoDocumento BIGINT AUTO_INCREMENT PRIMARY KEY,
    Descripcion VARCHAR(250)
);

CREATE TABLE USUARIOS (
    IdUsuario BIGINT AUTO_INCREMENT PRIMARY KEY,
    Apellido VARCHAR(250),
    Nombre VARCHAR(250),
    IdTipoDocumento BIGINT,
    Localidad VARCHAR(250),
    Direccion VARCHAR(250),
    Telefono VARCHAR(250),
    Correo VARCHAR(250),
    IdRol BIGINT,
    FOREIGN KEY (IdTipoDocumento) REFERENCES TIPODOCUMENTO(IdTipoDocumento),
    FOREIGN KEY (IdRol) REFERENCES ROLES(IdRol)
);

CREATE TABLE DESTINOS (
    IdDestino BIGINT AUTO_INCREMENT PRIMARY KEY,
    Titulo VARCHAR(250),
    Latitud VARCHAR(250),
    Longitud VARCHAR(250),
    Ciudad VARCHAR(250),
    Pais VARCHAR(250),
    Descripcion VARCHAR(250)
);

CREATE TABLE METODOS (
    IdMetodo BIGINT AUTO_INCREMENT PRIMARY KEY,
    Descripcion VARCHAR(250)
);

CREATE TABLE TIPOPAGO (
    IdTipoPago BIGINT AUTO_INCREMENT PRIMARY KEY,
    Tipo VARCHAR(250)
);

CREATE TABLE RESERVAS (
    IdReserva BIGINT AUTO_INCREMENT PRIMARY KEY,
    IdUsuario BIGINT,
    IdDestino BIGINT,
    IdMetodo BIGINT,
    IdTipoPago BIGINT,
    FOREIGN KEY (IdUsuario) REFERENCES USUARIOS(IdUsuario),
    FOREIGN KEY (IdDestino) REFERENCES DESTINOS(IdDestino),
    FOREIGN KEY (IdMetodo) REFERENCES METODOS(IdMetodo),
    FOREIGN KEY (IdTipoPago) REFERENCES TIPOPAGO(IdTipoPago)
);
